<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Alma.JsonApi</PackageId>
    <Version>8.2.1</Version>
    <RepositoryUrl>https://github.com/almacareer/prc-fjson-api.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/almacareer/prc-fjson-api</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src/Utils.fs" />
    <Compile Include="src/JsonApi.fs" />
    <Compile Include="src/Tracing.fs" />
    <Compile Include="src/Http.fs" />
  </ItemGroup>

  <Import Project=".paket\Paket.Restore.targets" />
</Project>
